server:
    port: 8099
spring:
    data:
        mongodb:
            uri: mongodb://mongo:27017/k8s_mongodb
    datasource:
        url: jdbc:mysql://mysql:3306/k8sdb?serverTimezone=Asia/Seoul
        username: k8suser
        password: k8suser
        driver-class-name: com.mysql.cj.jdbc.Driver

    devtools:
        restart:
            enabled: true

    application:
        name: login-app-service

    main:
        allow-bean-definition-overriding: true

    cloud:
        kubernetes:
            discovery:
                all-namespaces: true

    freemarker:
        cache: false
    thymeleaf:
        cache: false

mybatis:
    type-aliases-package: com.companyd.hompage.seoul.entity
    mapper-locations: mapper/*.xml